### ISSUE TITLE
Test on Windows

### ISSUE THREAD

**Issue by bartbutenaers** [bartbutenaers/node-red-contrib-xterm#3]
Currently the node has only been tested on Linux.  I can install it easily (thanks to the prebuilt binaries) on Windows 10, but then no information is displayed inside the terminal.  I have explained the cause in this Discourse [discussion](https://discourse.nodered.org/t/red-nodes-getnode-fails-on-windows-10/18069), but had no feedback yet :-(

**Comment by bartbutenaers** [comment]
Done.  Works fine

**Comment by Hugobox** [comment]
Hi Bart! 
I was curious to test this node. Currently on windows, the "Add 'enter' automatically" checkbox doesn't execute the command. Also if there are multiple commands in the terminal input node, they will arrive in the terminal on 1 line. 
Keep up the good work!

**Comment by bartbutenaers** [comment]
Hi @Hugobox,

Indeed I could reproduce the issue.  It worked only for a Linux backend and not for a Windows backend.
I have created a fix in the the *"node-pty-upgrade"* branch on Github.  Moreover it seemed that the prebuild binaries were not working correctly anymore for the recent NodeJs versions, so I have also updated those dependencies.

You can install the fix directly from my Github repo via this command (from within your .node-red folder):
```
npm install bartbutenaers/node-red-contrib-xterm#node-pty-upgrade
```
P.S. You need to have git installed...

Would be nice if you could test it, before I publish it on NPM!
Bart

**Comment by Hugobox** [comment]
Thanks Bart!
The "Add 'enter' automatically" checkbox now works beautifully! The only thing that still doesn't work is having multiple commands on different lines as they are treated as 1 big line.

**Comment by bartbutenaers** [comment]
@Hugobox,
Could you try to install it again?  Hopefully it is now better...

**Comment by Hugobox** [comment]
Works like a charm! Thank you!

**Comment by bartbutenaers** [comment]
@Hugobox,
Was forgotten to inform you that this fix is available in the Nide-RED palette.
Bart
